version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: validate_service.sh
      timeout: 300
      runas: root